version: "3"
services:
  mongo:
    image: mongo:4.2.0
    container_name: mongo-barmej
    ports:
      - "27017:27017"
  netflux:
    container_name: netflux
    build: .
    restart: on-failure
    ports:
      - 80:3000
    depends_on:
      - mongo
    env_file:
      - .env
